
name: Deploy to Dokku

on:
  pull_request:
    types: [ closed ]
    branches: [ master ]

jobs:
  deploy:

    runs-on: ubuntu-latest
    if: github.event.pull_request.merged

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Create appConfig file
      run: echo $APP_CONFIG_ENC | base64 -d > appConfig.json
      env:
        APP_CONFIG_ENC: ${{secrets.APP_CONFIG_ENC}

    - name: deploy
      uses: idoberko2/dokku-deploy-github-action@v1
      with:
        ssh-private-key: ${{ secrets.DOKKU_DEPLOY_KEY }}
        dokku-host: "dokku.fabyo.net"
        app-name: "devnots-api"
